// Crossrow multi-row affine-4/group-64 QMV for the MTP verify path.

#![allow(unsafe_code)]
//
// Port of the promoted mlx.fast kernel family (`qmv_fast_crossrow_affine4_g64`
// and its `_m` tail variants): the stock small-M dispatch runs one threadgroup
// per input row, so each verify row re-reads the same packed weight stream.
// The crossrow design instead launches ceil(M/IPG) x-groups per 8-output tile;
// every group shares its packed weight reads across the input rows it owns.
// Per-row arithmetic (lane->k mapping, load_vector scaling ladder, qdot mask
// order, fp32 simd_sum reduction, lane-0 store) is unchanged from the stock
// `qmv_fast` M=1 kernel, so every output element is bit-identical to the
// per-row reference — the property the MTP verifier's exact-greedy contract
// needs.
//
// Dispatch mirrors the promoted host logic:
//   - M2..M9: one compile-time schedule of one-, two-, or three-row groups
//   - K multiple of 512, N multiple of 8, group 64, bits 4, affine only.
#![allow(clippy::too_many_lines)]

use std::ffi::c_char;
use std::sync::OnceLock;

use mlx_rs::{Array, Stream, error::Exception};

struct CachedMetalKernel(mlx_sys::mlx_fast_metal_kernel);
unsafe impl Send for CachedMetalKernel {}
unsafe impl Sync for CachedMetalKernel {}

impl Drop for CachedMetalKernel {
    fn drop(&mut self) {
        unsafe { mlx_sys::mlx_fast_metal_kernel_free(self.0) }
    }
}

// ---------------------------------------------------------------------------
// Kernel header/body. Signature is generated by mlx_fast_metal_kernel_new:
// template <typename T, int GS, int M> kernel(w, sc, bi, x, y, K_size, N_size)
// ---------------------------------------------------------------------------

const CROSSROW_QMV_SOURCE: &str = r"
constexpr int SIMD_W = 32;
constexpr int ROWS_PER_SIMD = 4;
constexpr int VPT = 16;
constexpr int BLOCK = VPT * SIMD_W;
";

const fn crossrow_group_layout(t_rows: i32) -> &'static [i32] {
    match t_rows {
        2 => &[2],
        3 => &[2, 1],
        4 => &[2, 2],
        5 => &[3, 2],
        6 => &[3, 3],
        7 => &[3, 2, 2],
        8 => &[3, 3, 2],
        9 => &[3, 3, 3],
        _ => &[],
    }
}

fn crossrow_group_count(t_rows: i32) -> i32 {
    i32::try_from(crossrow_group_layout(t_rows).len()).unwrap_or(0)
}

fn push_crossrow_metal_schedule_function(
    source: &mut String,
    function_name: &str,
    emit_starts: bool,
) {
    use std::fmt::Write as _;
    let _ = writeln!(
        source,
        "template <int M>\ninline int {function_name}(int group) {{\n  switch (M) {{"
    );
    for m in 2..=9 {
        let _ = writeln!(source, "    case {m}:");
        let _ = writeln!(source, "      switch (group) {{");
        let mut first_m = 0;
        for (group, &group_size) in crossrow_group_layout(m).iter().enumerate() {
            let value = if emit_starts { first_m } else { group_size };
            let _ = writeln!(source, "        case {group}: return {value};");
            first_m += group_size;
        }
        let fallback = if emit_starts { -1 } else { 0 };
        let _ = writeln!(source, "        default: return {fallback};");
        let _ = writeln!(source, "      }}");
    }
    let fallback = if emit_starts { -1 } else { 0 };
    let _ = writeln!(source, "    default: return {fallback};");
    let _ = writeln!(source, "  }}");
    let _ = writeln!(source, "}}");
}

fn crossrow_metal_schedule_source() -> String {
    let mut source = String::new();
    push_crossrow_metal_schedule_function(&mut source, "crossrow_group_start", true);
    push_crossrow_metal_schedule_function(&mut source, "crossrow_group_size", false);
    source
}

// The kernel body source selects on M at runtime through template dispatch in
// a thin trampoline; mlx fast kernels compile per template instantiation.
const CROSSROW_QMV_ENTRY: &str = r"
{
  // The wrapper predeclares: template <typename OutT, int M> with inputs
  // w, sc, bi, x (OutT*), scalars K_size, N_size, output y (OutT*).
  const int K = KDIM;
  const int N = NDIM;
  const int in_vec_size_w = K / 2;
  const int in_vec_size_g = K / 64;

  uint3 tid = uint3(threadgroup_position_in_grid.x,
                    threadgroup_position_in_grid.y,
                    threadgroup_position_in_grid.z);
  uint sg = simdgroup_index_in_threadgroup;
  uint lid = thread_index_in_simdgroup;

  const int out_row = int(tid.y) * 8 + int(sg) * ROWS_PER_SIMD;


  // load_vector bits==4 (verbatim ladder)
  // Raw x load: higgs passes plain activations (not pre-scaled 4-bit x),
  // so unlike the vendored qmv_fast ladder there is no x-side dequant.
  // x is bf16 regardless of the f32 OutT the scales promotion selects.
  auto load_x4 = [](const device bfloat16_t* src, thread float* xt) {
    float sum = 0;
    for (int i = 0; i < VPT; ++i) {
      float v = float(src[i]);
      xt[i] = v;
      sum += v;
    }
    return sum;
  };

  // Fetch one 512-block of packed weights + group scale/bias for the 4
  // output rows this simdgroup owns.
  auto fetch_block = [&](int k, thread uint16_t pk[ROWS_PER_SIMD][4],
                         thread float scl[ROWS_PER_SIMD],
                         thread float bia[ROWS_PER_SIMD]) {
    for (int r = 0; r < ROWS_PER_SIMD; ++r) {
      const int row = out_row + r;
      const device uint16_t* ws = reinterpret_cast<const device uint16_t*>(
          reinterpret_cast<const device uint8_t*>(w) +
          row * in_vec_size_w + k / 2 + int(lid) * 8);
      for (int i = 0; i < 4; ++i) { pk[r][i] = ws[i]; }
      const int gi = row * in_vec_size_g + k / 64 + int(lid) / 4;
      scl[r] = float(sc[gi]);
      bia[r] = float(bi[gi]);
    }
  };

  // qdot bits==4 (verbatim mask lanes)
  auto qdot4 = [](const thread uint16_t* ws, const thread float* xt,
                  float scale, float bias, float sum) {
    float accum = 0;
    for (int i = 0; i < 4; i++) {
      accum += (xt[4 * i] * float((ws[i] & 0x000f)) +
                xt[4 * i + 1] * float((ws[i] >> 4) & 0x000f) +
                xt[4 * i + 2] * float((ws[i] >> 8) & 0x000f) +
                xt[4 * i + 3] * float((ws[i] >> 12) & 0x000f));
    }
    return scale * accum + sum * bias;
  };

  // One weight fetch, two x rows: per-chain order identical to qdot4.
  auto qdot4_pair = [](const thread uint16_t* ws,
                       const thread float* x0, const thread float* x1,
                       float scale, float bias, float2 sum) {
    float2 accum = 0.0f;
    for (int i = 0; i < 4; i++) {
      accum += (float2(x0[4 * i], x1[4 * i]) * float((ws[i] & 0x000f)) +
                float2(x0[4 * i + 1], x1[4 * i + 1]) * float((ws[i] >> 4) & 0x000f) +
                float2(x0[4 * i + 2], x1[4 * i + 2]) * float((ws[i] >> 8) & 0x000f) +
                float2(x0[4 * i + 3], x1[4 * i + 3]) * float((ws[i] >> 12) & 0x000f));
    }
    return scale * accum + sum * bias;
  };

  // One weight fetch, three x rows: each component retains qdot4's scalar
  // multiply/add order and remains an independent per-row accumulator.
  auto qdot4_triple = [](const thread uint16_t* ws,
                         const thread float* x0, const thread float* x1,
                         const thread float* x2, float scale, float bias,
                         float3 sum) {
    float3 accum = 0.0f;
    for (int i = 0; i < 4; i++) {
      accum += (float3(x0[4 * i], x1[4 * i], x2[4 * i]) * float((ws[i] & 0x000f)) +
                float3(x0[4 * i + 1], x1[4 * i + 1], x2[4 * i + 1]) * float((ws[i] >> 4) & 0x000f) +
                float3(x0[4 * i + 2], x1[4 * i + 2], x2[4 * i + 2]) * float((ws[i] >> 8) & 0x000f) +
                float3(x0[4 * i + 3], x1[4 * i + 3], x2[4 * i + 3]) * float((ws[i] >> 12) & 0x000f));
    }
    return scale * accum + sum * bias;
  };

  // ---- grouped path: the generated Rust-owned schedule maps group -> rows ----
  const int first_m = crossrow_group_start<M>(int(tid.x));
  const int group_size = crossrow_group_size<M>(int(tid.x));
  if (first_m >= 0 && group_size > 0) {
    thread float row_accum[3][ROWS_PER_SIMD];
    for (int mr = 0; mr < 3; ++mr) {
      for (int r = 0; r < ROWS_PER_SIMD; ++r) { row_accum[mr][r] = 0.0f; }
    }

    for (int k = 0; k < K; k += BLOCK) {
      thread uint16_t pk[ROWS_PER_SIMD][4];
      thread float scl[ROWS_PER_SIMD];
      thread float bia[ROWS_PER_SIMD];
      fetch_block(k, pk, scl, bia);
      thread float x0[VPT];
      const device bfloat16_t* xm0 = reinterpret_cast<const device bfloat16_t*>(x) + first_m * K + k + int(lid) * VPT;
      const float sum0 = load_x4(xm0, x0);
      if (group_size == 3) {
        thread float x1[VPT];
        thread float x2[VPT];
        const float sum1 = load_x4(xm0 + K, x1);
        const float sum2 = load_x4(xm0 + 2 * K, x2);
        for (int r = 0; r < ROWS_PER_SIMD; ++r) {
          const float3 partial = qdot4_triple(
              pk[r], x0, x1, x2, scl[r], bia[r], float3(sum0, sum1, sum2));
          row_accum[0][r] += partial.x;
          row_accum[1][r] += partial.y;
          row_accum[2][r] += partial.z;
        }
      } else if (group_size == 2) {
        thread float x1[VPT];
        const float sum1 = load_x4(xm0 + K, x1);
        for (int r = 0; r < ROWS_PER_SIMD; ++r) {
          const float2 partial = qdot4_pair(
              pk[r], x0, x1, scl[r], bia[r], float2(sum0, sum1));
          row_accum[0][r] += partial.x;
          row_accum[1][r] += partial.y;
        }
      } else {
        for (int r = 0; r < ROWS_PER_SIMD; ++r) {
          row_accum[0][r] += qdot4(pk[r], x0, scl[r], bia[r], sum0);
        }
      }
    }
    for (int r = 0; r < ROWS_PER_SIMD; ++r) {
      for (int mr = 0; mr < 3; ++mr) {
        if (mr < group_size) {
          const float reduced = simd_sum(row_accum[mr][r]);
          if (lid == 0) {
            y[(first_m + mr) * N + out_row + r] = static_cast<OutT>(reduced);
          }
        }
      }
    }
  }
}
";

static CROSSROW_QMV_KERNEL: OnceLock<CachedMetalKernel> = OnceLock::new();

fn crossrow_kernel() -> &'static CachedMetalKernel {
    CROSSROW_QMV_KERNEL.get_or_init(|| {
        let header = crossrow_metal_schedule_source();
        let source = format!("{CROSSROW_QMV_SOURCE}{CROSSROW_QMV_ENTRY}");
        let input_names: [&std::ffi::CStr; 4] = [c"w", c"sc", c"bi", c"x"];
        let output_names: [&std::ffi::CStr; 1] = [c"y"];
        let input_ptrs: Vec<*const c_char> = input_names.iter().map(|s| s.as_ptr()).collect();
        let output_ptrs: Vec<*const c_char> = output_names.iter().map(|s| s.as_ptr()).collect();
        let header_c =
            std::ffi::CString::new(header).unwrap_or_else(|_| std::ffi::CString::default());
        let source_c =
            std::ffi::CString::new(source).unwrap_or_else(|_| std::ffi::CString::default());
        unsafe {
            let in_vec = mlx_sys::mlx_vector_string_new_data(
                input_ptrs.as_ptr().cast_mut(),
                input_ptrs.len(),
            );
            let out_vec = mlx_sys::mlx_vector_string_new_data(
                output_ptrs.as_ptr().cast_mut(),
                output_ptrs.len(),
            );
            let kernel = mlx_sys::mlx_fast_metal_kernel_new(
                c"higgs_crossrow_qmv_affine4_g64".as_ptr(),
                in_vec,
                out_vec,
                source_c.as_ptr(),
                header_c.as_ptr(),
                false,
                false,
            );
            mlx_sys::mlx_vector_string_free(in_vec);
            mlx_sys::mlx_vector_string_free(out_vec);
            CachedMetalKernel(kernel)
        }
    })
}

/// Eligibility: affine 4-bit group-64, `bf16`/`fp16` x, `M` in 2..=9,
/// `K % 512 == 0`, `N % 8 == 0`. The caller (`QLinear::forward`) supplies
/// a `[T, K]` x and the packed `[N, K/8]` weight triple.
pub fn crossrow_qmv_verify(
    x: &Array,
    weight: &Array,
    scales: &Array,
    biases: &Array,
    t_rows: i32,
) -> Result<Array, Exception> {
    let grid_x = crossrow_group_count(t_rows);
    if grid_x == 0 {
        return Err(Exception::custom("crossrow_qmv: unsupported row schedule"));
    }
    let [n_rows, k_packed] = *weight.shape() else {
        return Err(Exception::custom("crossrow_qmv: weight not 2D"));
    };
    let k_dim = k_packed * 8;
    let x_flat = x.reshape(&[t_rows, k_dim])?;
    let stream = Stream::task_local_or_default();
    // Stock quantized_matmul promotes to the scales dtype (f32 for our
    // checkpoints); match it so per-row outputs round identically.
    let out_dtype = unsafe { mlx_sys::mlx_array_dtype(scales.as_ptr()) };

    let kernel = crossrow_kernel();
    unsafe {
        let config = mlx_sys::mlx_fast_metal_kernel_config_new();
        mlx_sys::mlx_fast_metal_kernel_config_add_template_arg_dtype(
            config,
            c"OutT".as_ptr(),
            out_dtype,
        );
        mlx_sys::mlx_fast_metal_kernel_config_add_template_arg_int(config, c"M".as_ptr(), t_rows);
        mlx_sys::mlx_fast_metal_kernel_config_add_template_arg_int(config, c"KDIM".as_ptr(), k_dim);
        mlx_sys::mlx_fast_metal_kernel_config_add_template_arg_int(
            config,
            c"NDIM".as_ptr(),
            n_rows,
        );
        // grid: x follows the Rust-owned row schedule; y covers 8-output tiles.
        let grid_y = usize::try_from(n_rows).map_or(0, |n| n.saturating_add(7) / 8);
        // mlx fast kernels dispatch THREADS (dispatch_threads), so the grid
        // is total thread counts: gx groups * 64 threads each.
        let gx = grid_x.saturating_mul(64);
        let gy = i32::try_from(grid_y).unwrap_or(0);
        mlx_sys::mlx_fast_metal_kernel_config_set_grid(config, gx, gy, 1);
        mlx_sys::mlx_fast_metal_kernel_config_set_thread_group(config, 64, 1, 1);
        if std::env::var("HIGGS_CROSSROW_VERBOSE").is_ok() {
            mlx_sys::mlx_fast_metal_kernel_config_set_verbose(config, true);
        }
        let out_shape = [t_rows, n_rows];
        mlx_sys::mlx_fast_metal_kernel_config_add_output_arg(
            config,
            out_shape.as_ptr(),
            out_shape.len(),
            out_dtype,
        );

        let input_ptrs = [
            weight.as_ptr(),
            scales.as_ptr(),
            biases.as_ptr(),
            x_flat.as_ptr(),
        ];
        let inputs =
            mlx_sys::mlx_vector_array_new_data(input_ptrs.as_ptr().cast_mut(), input_ptrs.len());
        let mut result = mlx_sys::mlx_vector_array_new();
        let status = mlx_sys::mlx_fast_metal_kernel_apply(
            &raw mut result,
            kernel.0,
            inputs,
            config,
            stream.as_ptr(),
        );
        mlx_sys::mlx_fast_metal_kernel_config_free(config);
        mlx_sys::mlx_vector_array_free(inputs);
        if status != 0 {
            mlx_sys::mlx_vector_array_free(result);
            return Err(Exception::custom("crossrow_qmv kernel apply failed"));
        }
        let len = mlx_sys::mlx_vector_array_size(result);
        if len != 1 {
            mlx_sys::mlx_vector_array_free(result);
            return Err(Exception::custom(
                "crossrow_qmv kernel returned unexpected output count",
            ));
        }
        let mut out = mlx_sys::mlx_array_new();
        mlx_sys::mlx_vector_array_get(&raw mut out, result, 0);
        mlx_sys::mlx_vector_array_free(result);
        Ok(Array::from_ptr(out))
    }
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::panic,
        clippy::unwrap_used,
        clippy::expect_used,
        unsafe_code,
        clippy::as_conversions,
        clippy::cast_precision_loss
    )]
    use super::*;
    use mlx_rs::ops;

    fn assert_crossrow_matches_stock(
        case: &str,
        x: &Array,
        w: &Array,
        s: &Array,
        b: &Array,
        m: i32,
        k: i32,
    ) {
        let got = crossrow_qmv_verify(x, w, s, b, m).unwrap();
        assert_eq!(got.dtype(), s.dtype(), "{case} M={m}: output dtype");
        let mut rows = Vec::new();
        for r in 0..m {
            let xr = x
                .take_axis(Array::from_slice::<i32>(&[r], &[1]), 0)
                .unwrap();
            let yr =
                ops::quantized_matmul(xr.reshape(&[1, k]).unwrap(), w, s, b, true, 64, 4).unwrap();
            rows.push(yr);
        }
        let want = ops::concatenate_axis(&rows.iter().collect::<Vec<_>>(), 0).unwrap();

        let got_f32 = got.as_dtype(mlx_rs::Dtype::Float32).unwrap();
        got_f32.eval().unwrap();
        let want_f32 = want.as_dtype(mlx_rs::Dtype::Float32).unwrap();
        let diff = ops::abs(ops::subtract(&got_f32, &want_f32).unwrap()).unwrap();
        let max_diff: f32 = ops::max(&diff, None).unwrap().item();
        assert!(
            max_diff == 0.0,
            "{case} M={m}: crossrow diverged (max diff {max_diff})"
        );
    }

    #[test]
    fn crossrow_group_layout_covers_supported_rows() {
        let expected = [
            (2, &[2][..]),
            (3, &[2, 1][..]),
            (4, &[2, 2][..]),
            (5, &[3, 2][..]),
            (6, &[3, 3][..]),
            (7, &[3, 2, 2][..]),
            (8, &[3, 3, 2][..]),
            (9, &[3, 3, 3][..]),
        ];
        for (rows, groups) in expected {
            assert_eq!(crossrow_group_layout(rows), groups);
            assert_eq!(
                crossrow_group_count(rows),
                i32::try_from(groups.len()).unwrap_or(0)
            );
            assert_eq!(groups.iter().sum::<i32>(), rows);
        }
    }

    #[test]
    fn crossrow_group_layout_rejects_unsupported_rows() {
        for rows in [i32::MIN, -1, 0, 1, 10, i32::MAX] {
            assert!(crossrow_group_layout(rows).is_empty());
            assert_eq!(crossrow_group_count(rows), 0);
        }
    }

    #[test]
    fn crossrow_metal_schedule() {
        fn schedule_case(m: i32, values: &[i32], fallback: i32) -> String {
            use std::fmt::Write as _;
            let mut branch = format!("    case {m}:\n      switch (group) {{\n");
            for (group, value) in values.iter().enumerate() {
                let _ = writeln!(branch, "        case {group}: return {value};");
            }
            let _ = write!(branch, "        default: return {fallback};\n      }}\n");
            branch
        }

        let source = crossrow_metal_schedule_source();
        for m in 2..=9 {
            let mut first_m = 0;
            let mut starts = Vec::new();
            for &group_size in crossrow_group_layout(m) {
                starts.push(first_m);
                first_m += group_size;
            }
            assert!(
                source.contains(&schedule_case(m, &starts, -1)),
                "missing M={m} starts {starts:?}"
            );
            assert!(
                source.contains(&schedule_case(m, crossrow_group_layout(m), 0)),
                "missing M={m} sizes {:?}",
                crossrow_group_layout(m)
            );
        }

        assert!(source.contains(&schedule_case(8, &[3, 3, 2], 0)));
        assert!(source.contains(&schedule_case(9, &[3, 3, 3], 0)));
    }

    /// Every M in 2..=9 must produce bit-identical rows to stock
    /// `quantized_matmul` executed per row (the exactness contract the MTP
    /// verifier relies on).
    #[test]
    fn crossrow_bit_exact_vs_stock_rows() {
        let shapes: [(i32, i32); 3] = [(512, 5120), (5120, 17408), (1024, 5120)];
        for (n, k) in shapes {
            // Diverse nibbles: row i, col j -> ((i*7 + j*13) % 15 - 7) / 8
            let n_i: i32 = n;
            let k_i: i32 = k;
            let mut host = Vec::with_capacity(usize::try_from(n_i * k_i).unwrap_or(0));
            for i in 0..n_i {
                for j in 0..k_i {
                    let q = ((i * 7 + j * 13).rem_euclid(15)) - 7;
                    host.push(q as f32 / 8.0);
                }
            }
            let w32 = Array::from_slice::<f32>(&host, &[n, k]);
            let (w, s, b) = ops::quantize(&w32, Some(64), Some(4)).unwrap();
            for m in 2..=9i32 {
                let m_i: i32 = m;
                let mut xhost = Vec::with_capacity(usize::try_from(m_i * k).unwrap_or(0));
                for i in 0..m_i {
                    for j in 0..k {
                        xhost.push((((i + 1) * (j % 97)) % 31) as f32 / 16.0 - 1.0);
                    }
                }
                let x32 = Array::from_slice::<f32>(&xhost, &[m, k]);
                let x = x32.as_dtype(mlx_rs::Dtype::Bfloat16).unwrap();
                assert_crossrow_matches_stock(
                    &format!("baseline N={n} K={k}"),
                    &x,
                    &w,
                    &s,
                    &b,
                    m,
                    k,
                );
            }
        }

        // Direct packed words make the edge nibbles explicit: complete rows
        // of 0x0, complete rows of 0xf, and alternating 0/f nibbles.
        let (n, k) = (8i32, 512i32);
        let words_per_row = k / 8;
        let mut packed = Vec::with_capacity(usize::try_from(n * words_per_row).unwrap_or(0));
        for row in 0..n {
            for word in 0..words_per_row {
                packed.push(match row {
                    0 => 0x0000_0000,
                    1 => 0xffff_ffff,
                    _ if word % 2 == 0 => 0xf0f0_f0f0,
                    _ => 0x0f0f_0f0f,
                });
            }
        }
        let w = Array::from_slice::<u32>(&packed, &[n, words_per_row]);
        let groups_per_row = k / 64;
        let mut scales = Vec::with_capacity(usize::try_from(n * groups_per_row).unwrap_or(0));
        let mut biases = Vec::with_capacity(usize::try_from(n * groups_per_row).unwrap_or(0));
        for row in 0..n {
            for group in 0..groups_per_row {
                scales.push(if (row + group) % 2 == 0 {
                    0.125
                } else {
                    -0.0625
                });
                biases.push(if group % 2 == 0 { -0.5 } else { 0.25 });
            }
        }
        let s = Array::from_slice::<f32>(&scales, &[n, groups_per_row]);
        let b = Array::from_slice::<f32>(&biases, &[n, groups_per_row]);

        for m in [6i32, 8, 9] {
            let mut activations = Vec::with_capacity(usize::try_from(m * k).unwrap_or(0));
            for row in 0..m {
                for col in 0..k {
                    let value = match row {
                        0 => 0.0,
                        1 => -((col % 17 + 1) as f32) / 16.0,
                        _ => {
                            let magnitude = (((row + 1) * (col % 11 + 1)) % 31 + 1) as f32 / 32.0;
                            if (row + col) % 2 == 0 {
                                magnitude
                            } else {
                                -magnitude
                            }
                        }
                    };
                    activations.push(value);
                }
            }
            let x = Array::from_slice::<f32>(&activations, &[m, k])
                .as_dtype(mlx_rs::Dtype::Bfloat16)
                .unwrap();
            assert_crossrow_matches_stock(
                "adversarial zero/max nibbles and signed activations",
                &x,
                &w,
                &s,
                &b,
                m,
                k,
            );
        }
    }
}
